# Generated by Django 2.0.3 on 2018-03-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_crusttype_pizzasize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crusttype',
            name='crust',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pizzasize',
            name='sizes',
            field=models.IntegerField(max_length=10),
        ),
    ]
